### ISSUE TITLE
Credit Missing

### ISSUE THREAD

**Issue by jagrosh** [ultimate255/SkyeBot#1]
A large portion of the code in this repository is a direct copy of the code in a previous commit in my repository, https://github.com/jagrosh/Vortex

The following files are unmodified (or very slightly modified) copies of files from my repo that have had the headers changed to remove my license. Please edit these files to restore my license and credit:
`Command.java`
`AboutCmd.java`
`PingCmd.java`
`WaitingEvent.java`
`FormatUtil.java`

**Comment by ultimate255** [comment]
Done, also added credit on readme.

**Comment by jagrosh** [comment]
Wonderful, thank you!
